sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - EXECUTE_STATIC_ANALISYS_CHECK=true
        - EXECUTE_CS_CHECK=true
        - EXECUTE_TEST_SCRUTINIZER=true
        - DEPS=locked
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4snapshot
      env:
        - DEPS=lowest
    - php: 7.4snapshot
      env:
        - DEPS=latest
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=latest

  allow_failures:
    - php: nightly
    - php: 7.4snapshot
      env:
        - DEPS=lowest

install:
  - if [[ $DEPS == 'locked' ]]; then travis_retry composer install $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi

script:
  - if [[ EXECUTE_STATIC_ANALISYS_CHECK == 'true' ]]; then composer phpstan ; fi
  - if [[ EXECUTE_STATIC_ANALISYS_CHECK == 'true' ]]; then composer psalm ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover coverage.clover ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi